name: CI

on:
  push:
    branches: [ master, respostas ]
  pull_request:
    branches: [ master, respostas ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 
    - name: Build
      run: docker build . -t app
    - name: Run PHP unit tests
      run:  docker run app vendor/bin/phpunit --whitelist ./src/Service --coverage-text --colors ./tests
    - name: Run application
      run: docker run app php ./getIp.php